/* Balanced-mode strength corrections per species, multiplied into health and damage.
   Generated by "node tools/arena-sim.js tune": 16 rounds of 450 full matches, stochastic approximation averaged over the last 8.
   Regenerate rather than edit by hand. */
(function(root){
  var L = root.Ludus = root.Ludus || {};
  L.ArenaTuning = {
    agouti: 1.040,
    howler: 0.967,
    capybara: 0.940,
    tapir: 0.917,
    ocelot: 1.085,
    harpy: 1.047,
    jaguar: 1.021,
    anaconda: 0.987,
    otter: 1.064,
    caiman: 0.956,
    peccary: 1.013,
    spider: 1.023,
    bushmaster: 0.957
  };
})(typeof window !== 'undefined' ? window : globalThis);
